### PR TITLE
Update 5a_environlist.c

### PR DESCRIPTION
**Pull request by Jaiswal-ruhil**
no need for an extra variable

### CODE REVIEW

**Comment by KarthikNayak** [comment]
Hello @Jaiswal-ruhil ,
Thanks for the pull request, But unfortunately your commit does not adhere to the
[guidelines](https://github.com/fsmk/CS-VTU-Lab-Manual/wiki/Guidelines-for-Contribution) mentioned. Please go through the guidelines and amend your commit and send a pull request. 
Thanks,
Karthik

**Comment by arunisaac** [comment]
This has been fixed in the latex branch.
See https://github.com/fsmk/CS-VTU-Lab-Manual/blob/latex/VTU/Sem6/USP_CD_Lab/05aEnvironmentVariables/environment_variables.c

Once work in the latex branch is finished, it will be merged with the master branch.

**Comment by KarthikNayak** [comment]
@arunisaac This patch tries to achieve something different from what your patch does,
This patch tries to eliminate the need of the `char **ptr` variable.

**Comment by arunisaac** [comment]
@KarthikNayak 
Yes, I understand that.

The original code had both an int i and a char** ptr variable. Only one of the two variables is required. The original code wasn't doing anything with the int i variable at all. So, my patch just removed that variable. Jaiswal-ruhil's code eliminates the ptr variable instead. These are just two different ways of eliminating the redundancy.

Anyways, considering that Jaiswal-ruhil's code looks a little bit more elegant without all the pointers in my code, I'll change my code to his style.

**Comment by arunisaac** [comment]
The code has been changed in the latex branch.
https://github.com/fsmk/CS-VTU-Lab-Manual/blob/latex/VTU/Sem6/USP_CD_Lab/05aEnvironmentVariables/environment_variables.c

Thanks for the pull request. I am now closing this thread.

**Pull request closed without merging**
