### PR TITLE
V/: Fixed header syntax in all the `.md` files in the project.

### PR DESCRIPTION
**Pull request by kaushikthedeveloper**
Final count :
- 399 occurences
- 81 files

Example of the change :
- previously
```markdown
###Header
```
- current fixes
```markdown
### Header
```

_Note : for anyone wondering how, hint -> `Regex`_

### CODE REVIEW

**Comment by KarthikNayak** [comment]
@kaushikthedeveloper thanks for the commit, been due for a while. Do you mind sharing the regex (the sed command, or alternative) that you used. Perhaps edit the commit to include that into the description?

**Comment by KarthikNayak** [comment]
While you're at it, maybe change the description with a little more explanation?

**Comment by cyberhck** [comment]
Thanks for taking time to create this PR, I really appreciate it :slightly_smiling_face: as @KarthikNayak requested, if you don't mind the command you used to do all these, that'd be nice.

I'm gonna merge this now (since this is a one time task and next time, we'll be catching this during review hopefully), and this PR does exactly what it says and nothing more and nothing else (which is exactly what we want).

**Comment by KarthikNayak** [comment]
@cyberhck  Please refrain from merging before doing a normal sanity test. This commit breaks for sub-headings. E.g `###Design` becomes `## Design` instead of `### Design`. That's why I asked for the regex used. Also what good is the guidelines if it isn't enforced? 

Reverting the commit.

**Comment by KarthikNayak** [comment]
@kaushikthedeveloper Please re-open the commit when you edit the description and perhaps fix and mentions the regex.

**Comment by cyberhck** [comment]
@KarthikNayak I'm sorry, I scrolled down a little bit and I saw that everything was fine, not sure how I missed bunch of those, reverting sounds like a good idea, again, sorry about that.

**Comment by KarthikNayak** [comment]
@cyberhck that's alright. But do refrain from merging when someone is asking for clarification. Also the "this one time" attitude should be discouraged.

**Comment by cyberhck** [comment]
I meant, one time task, sorry about that again, I thought you also went through the changes, and didn't notice anything. Maybe you did after the merge. (if you had noticed before, I'd suggest you to use Github's review feature and request changes :slightly_smiling_face: )

**Comment by KarthikNayak** [comment]
I was waiting for the regex, to see if there are more bugs.    I think you're not understanding my intentions. It's more to do with following the guidelines. You can't have a commit which touches 81 and doesn't explain how it did so. I also don't understand how you think you'd manually test something like this, in reference to "I scrolled down a little bit and I saw that everything was fine". You just DON'T merge commits by scrolling down a little. That's just not how CR's are done. 

Plus it's very impolite to merge a PR when someone is reviewing it and asking for clarification from the developer.

I'm sure you know that it's infeasible to use "review feature" for a commit that touches 81 files. Maybe I was just wrong in assuming you'd understand that. Sorry. 

@cyberhck

**Comment by kaushikthedeveloper** [comment]
@KarthikNayak  @cyberhck : Sorry about that. Knew I was forgetting something, but was busy with something else and didn't notice back then. It was because I forgot to add the look-back on the Regex.

Noticed that @KarthikNayak has reverted back the changes. Will provide a new PR and with the correct changes.

**Pull request merged**
