### PR TITLE
Use glMultMatrix for rotation in VTU/Sem6/CG_Lab/04RotateHouse

### PR DESCRIPTION
**Pull request by upman**
The code is much more clear this way and also aids the understanding of OpenGL's transformation matrix.

### CODE REVIEW

**Comment by dash-rai** [comment]
Since the question for this program says "using OpenGL functions", wouldn't it be better just to use `glRotatef`?

**Comment by upman** [comment]
glRotatef generates a rotation matrix that rotates around the origin and multiplies that to the transformation matrix.

It would require a translate to bring the point around which we wish to rotate to the origin before we rotate and then a translate back.

I think this is a good way to do it in a lab program since they're more about demonstrating concepts than getting stuff to work. Besides, VTU seems to dislike conciseness in code :P

**Comment by KarthikNayak** [comment]
@upman First things first, please refer to the the [guidelines](https://github.com/fsmk/CS-VTU-Lab-Manual/wiki/Guidelines-for-Contribution), as your commit message does not adhere to the one mentioned in the guideline.
Like @dash-rai  suggested, an easier solution would be to use `glRotatef` and `glTranslatef`  together, which would remove the complexity of calculating the rotation matrix.
Also `GLfloat rot_mat[16]` would be better off as `GLfloat rot_mat[4][4]` wouldn't it? That would give it the identity of a transformation matrix.

**Comment by KarthikNayak** [comment]
No response from @upman. Closing it

**Pull request closed without merging**
