### PR TITLE
V/6/USP/05aEnvironList: remove unneeded code

### PR DESCRIPTION
**Pull request by SubhrajyotiSen**
Sorry for multiple commits. Please Squash 😄

### CODE REVIEW

**Comment by KarthikNayak** [comment]
```diff
- exit(0);
￼+ return 0;
```

This is not justified by the commit message, nor is there any indication of why this is being done. It would be better if you explain the intention behind this. Perhaps two commits? one removing unused `int` and another converting `exit` to `return`. Of course, after explaining the intent :+1:

**Comment by cyberhck** [comment]
I might be wrong here, but the intent for removing `exit(0)` might be because it's exits the whole program, and `return 0` will exit only the function, there's no problem with using either of those when it's inside `main`. In both case program will terminate and the `atexit` handlers will be called.

However if we decide to break that down to a function, it'd make sense not to do an exit of course.

That's my opinion of course

**Comment by SubhrajyotiSen** [comment]
@cyberhck is right. I used `return 0` for the intent of just exiting the function and also to bring it in line with 1c86ab136bff179d2227ad7c683a16f6adbc006a . I should have mentioned it in the commit message. Sorry for that. Should I make a new PR?

**Comment by KarthikNayak** [comment]
@cyberhck @SubhrajyotiSen I understand the difference, I mean it needs to be specified in the commit message. Also these are two different changes squashed into one commit. 

What I recommend:
commit 1: change exit to return
commit 2: remove unused variable

By this I mean, that commit messages are better grouped by what they are doing, for example you have 3 different commits since your modifying three different files, but doing the same things (although you have combined change of exit and removal of unused variable). It makes more sense to group by action. Where you have two commits as I mentioned above, each modifying the required files. 

Could you do that and PR?

**Comment by SubhrajyotiSen** [comment]
Yes. Grouping by action does make more sense. I'll make a fresh PR. 
Thanks

**Pull request closed without merging**
