### PR TITLE
V/6/USP/05aEnvironList: remove unused variable and change exit method

### PR DESCRIPTION
**Pull request by SubhrajyotiSen**
`int i` is defined but never used in the program
`exit(0)` will exit the program. But `return 0` will exit the function. Also brings it inline with 1c86ab1

### CODE REVIEW

**Comment by KarthikNayak** [comment]
LGTM, commit messages doesn't follow the contribution guidelines, but that's minor and I'll manually add that in before merging. Just make sure you follow next time

**Comment by SubhrajyotiSen** [comment]
I'll take care next time

**Comment by SubhrajyotiSen** [comment]
How did the conflicts even arise? It was a clean PR

**Comment by KarthikNayak** [comment]
What merge conflicts are you talking about, its in master.

**Pull request closed without merging**
