### PR TITLE
V/6/CS/01Serpinski: modified algo (draws tetrahedron instead of trian…

### PR DESCRIPTION
**Pull request by Jaiswal-ruhil**
the previous algo made triangles in the phase. this draws the tetrahedron shapes recursively

### CODE REVIEW

**Comment by KarthikNayak** [comment]
Hello @Jaiswal-ruhil 
What is the benefit of doing this?
The previous code would split each side of the tetrahedron recursively. This splits the entire tetrahedron recursively. The problem with this patch is that we wont have each side of the original tetrahedron to be a single color. This will mix the colors up. Also why remove the "void triangle(point a,point b,point c)" ?

**Comment by Jaiswal-ruhil** [comment]
for the color problem : this can b done:
        divide_tetrahedron(a,ab,ac,ad,m-1);	
        divide_tetrahedron(ab,b,bc,bd,m-1);
        divide_tetrahedron(ac,bc,c,cd,m-1);
        divide_tetrahedron(ad,bd,cd,d,m-1);

and sry about the draw_triangle: while debugging i just changed it and then did not revert back

**Comment by Jaiswal-ruhil** [comment]
the benefit of this approach is
 it is universal: can be applied to any shape

**Comment by Jaiswal-ruhil** [comment]
i just tested the previous code the output is not correct
it does not create proper tetrahedron for the inner iterations
to be sure just try and rotate the gasket u will find the error

**Comment by KarthikNayak** [comment]
@Jaiswal-ruhil Do we want that benefit? I mean the problem statement is quite specific here, and the use of the lab manual is to render to these specific problems.

If I'm not mistaken this is the method used and prescribed in the VTU Prescribed TextBook.

**Comment by dash-rai** [comment]
@KarthikNayak, I think it's better to be splitting the tetrahedrons than splitting triangles. It is more intuitive and is the right way to do it.

Just drawing the outer face is noticeable even if no rotation is done and some teachers might have issues with that. We're currently not drawing a 3D Sierpinski gasket, but drawing four 2D Sierpinski gaskets and they aren't the same.

The only benefit of what we have is that we can have different colours on each side (not a necessity) and @Jaiswal-ruhil says he can fix that as well.

**Comment by KarthikNayak** [comment]
@dash-rai good point!

@Jaiswal-ruhil Could you pull another request with the fixes?

**Comment by Jaiswal-ruhil** [comment]
already fixed the color problem. in commit 7d5df5309cab52ffc1694fb175e2c941bdb8e20d

**Comment by KarthikNayak** [comment]
@Jaiswal-ruhil will merge, thanks :)

**Pull request closed without merging**
