### PR TITLE
ns-2 Programs added to 7th sem CN lab.

### PR DESCRIPTION
**Pull request by Rahul147**
All 7th sem simulation programs written in NS-2(network simulator) and processed for data using AWK scripts.

### CODE REVIEW

**Comment by KarthikNayak** [comment]
Hello,
Thanks for taking the time off to send PR's, But the commit messages themselves do not comply with what we follow in this repo. Do have a look at https://github.com/fsmk/CS-VTU-Lab-Manual/wiki/Guidelines-for-Contribution#2-describe-your-changes-well. Thanks.

**Comment by KarthikNayak** [comment]
@Rahul147 any updates?

**Comment by Rahul147** [comment]
Hey,

I'll start working on it, I was not well and I'm recovering.

**Comment by cyberhck** [comment]
Hi @Rahul147 , can you send separate PR for each file? In that way it helps us to test everything individually and if one of them doesn't work, we can still merge the rest. Also can you document on how we actually execute these programs, for someone who just started 7th sem, it'd be great if you tell them what packages to install and stuff.

Thanks.

**Comment by Rahul147** [comment]
Hi, sure i'll start doing that, will get back to you guys at the earliest.

**Comment by cyberhck** [comment]
https://www.youtube.com/watch?v=arj7oStGLkU

**Comment by Rahul147** [comment]
Sorry guys, I just don't have the time to get it done. I'll closing the request.

**Pull request closed without merging**
